// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLac6HXff5bNrhqBMMHPCbWAPwtpDN2UA',
    appId: '1:1094774088630:web:d739ab477701a7dbd91717',
    messagingSenderId: '1094774088630',
    projectId: 'governmentjobs-e96f8',
    authDomain: 'governmentjobs-e96f8.firebaseapp.com',
    storageBucket: 'governmentjobs-e96f8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM9hBRJbsQsWsV_JUaUYYpscJhW2pQt4g',
    appId: '1:1094774088630:android:30c54ebcd481d959d91717',
    messagingSenderId: '1094774088630',
    projectId: 'governmentjobs-e96f8',
    storageBucket: 'governmentjobs-e96f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiSfAYByjZwbjJmuVC0o5SgYinSQTgZDQ',
    appId: '1:1094774088630:ios:73dc853c8c9adeb8d91717',
    messagingSenderId: '1094774088630',
    projectId: 'governmentjobs-e96f8',
    storageBucket: 'governmentjobs-e96f8.appspot.com',
    androidClientId: '1094774088630-c9849vgnlupgqt7ac1t9s48abtblhevk.apps.googleusercontent.com',
    iosClientId: '1094774088630-o1ajc28k1eub0alb8oq5gcibmps9gq3j.apps.googleusercontent.com',
    iosBundleId: 'com.example.governmentjob',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiSfAYByjZwbjJmuVC0o5SgYinSQTgZDQ',
    appId: '1:1094774088630:ios:73dc853c8c9adeb8d91717',
    messagingSenderId: '1094774088630',
    projectId: 'governmentjobs-e96f8',
    storageBucket: 'governmentjobs-e96f8.appspot.com',
    androidClientId: '1094774088630-c9849vgnlupgqt7ac1t9s48abtblhevk.apps.googleusercontent.com',
    iosClientId: '1094774088630-o1ajc28k1eub0alb8oq5gcibmps9gq3j.apps.googleusercontent.com',
    iosBundleId: 'com.example.governmentjob',
  );
}
